### ISSUE TITLE
Wann kommt hier endlich mal content?

### ISSUE THREAD

**Issue by droggl** [Padu98/Stundenplan#1]
Ich warte seit Ewigkeiten auf Fortschritte bei der Entwicklung des Stundenplans. Aktuell habe ich überhaupt keine Übersicht über meine Vorlesungen und es herrscht totales Chaos. Der Stundenplan wäre meine Rettung!  Wann kann man hier mit Fortschritten rechnen?

**Comment by Padu98** [comment]
Hello @droggl,

unfortunately this project is currently "auf Eis gelegt". We plan to publish the next release which is version 0.0.2 in 2099. Till then feel free so use the current version 0.0.1 of Stundenplan: 

https://github.com/Padu98/Stundenplan

If you have other question don't be shy to open another issue. I am going to close this on for now. 
love <3 Padu98
